### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by ProtoBoyGG** [shubhamoy/justdialscraper#1]
Scraping Page 1
Traceback (most recent call last):
  File "justdialscraper.py", line 31, in <module>
    if not resp.json()['paidDocIds']:
  File "C:\Users\hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\hp\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

C:\Users\hp\Downloads\Compressed\justdialscraper-master\justdialscraper-master>

**Comment by shubhamoy** [comment]
Kindly add the url you tried to scrape

**Comment by poplipopatpotty** [comment]
https://www.justdial.com/Delhi/Bhangra-Dance-Troupe/nct-10993593

**Comment by poplipopatpotty** [comment]
Are you on Discord, the conversation it is natural there.
